version: '3.8'
services:
  mysql:
    image: mysql:5.5.48
    container_name: mysql
    restart: always
    ports:
      - "5548:3306"
    volumes:
      - ./env/mysql/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  php:
    build: ./env/php
    container_name: php
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html